services:
  mongo:
    container_name: mongodb
    image: 'mongo:4.2.24-bionic'
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: yamaha
    volumes:
      - ./data:/data/db